### ISSUE TITLE
Doubts on duplicate policy

### ISSUE THREAD

**Issue by hulimatata** [RedisTimeSeries/redistimeseries-py#86]
redis.exceptions.ResponseError: TSDB: Error at upsert, update is not supported in BLOCK mode

How to solve this problem

**Comment by filipecosta90** [comment]
@hulimatata since [RedisTimeSeries 1.4](https://github.com/RedisTimeSeries/RedisTimeSeries/releases/tag/v1.4.5) we've added the ability to back-fill time series, with different duplicate policies.

The following are the possible policies:

   * BLOCK - an error will occur for any out of order sample
   * FIRST - ignore the new value
   * LAST - override with latest value
   * MIN - only override if the value is lower than the existing value
   * MAX - only override if the value is higher than the existing value
   * SUM - If a previous sample exists, add the new sample to it so that the updated value is equal to (previous + new). If no previous sample exists, set the updated value equal to the new value.

 The default behavior is to block updates to the same timestamp. 

You can check our docs more in deep section about duplicate policy here: https://oss.redislabs.com/redistimeseries/configuration/#duplicate_policy.

Let's check with two python examples:

**default:  BLOCK - an error will occur for any out of order sample**
```python
from redistimeseries.client import Client
rts = Client()
rts.create('block-upsert', labels={'Time':'Series'})
rts.add('block-upsert', 1, 10.0)
rts.add('block-upsert', 1, 5.0)
```
This block of code should output the following exception: 

```
redis.exceptions.ResponseError: TSDB: Error at upsert, update is not supported in BLOCK mode
```
-----

**LAST - override with latest value**
```python
from redistimeseries.client import Client
rts = Client()
rts.create('last-upsert', labels={'Time':'Series'},duplicate_policy='last')
rts.add('last-upsert', 1, 10.0)
rts.add('last-upsert', 1, 5.0)
# should output [(1, 5.0)]
print(rts.range('last-upsert', 0, -1))
```

This block of code should output the following exception: 
```
[(1, 5.0)]
```

@hulimatata I believe we should add further notes about duplicate policy to the Readme ( this is recurrent question ). Will open a PR about it @gkorland
